<?php

namespace Bigfoot\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Routing\Exception\ResourceNotFoundException;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\RouterInterface;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository implements RouterInterface
{
    public function getRouteCollection()
    {
    }

    public function match($pathinfo)
    {
        if ($this->findOneByUrl($pathinfo)) {
            die('Found !');
        }

        throw new ResourceNotFoundException();
    }

    public function setContext(RequestContext $context)
    {

    }

    public function getContext()
    {

    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {

    }
}
