<?php

namespace Bigfoot\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranslatableLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslatableLabelRepository extends EntityRepository
{
    /**
     * @param $locale
     * @param $domain
     */
    public function findAllForLocaleAndDomain($locale, $domain)
    {
        return $this
            ->createQueryBuilder('t')
            ->andWhere('t.domain = :domain')
            ->setParameter(':domain', $domain)
            ->getQuery()
            ->setHint(
                \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
                'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
            )
            ->setHint(
                \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
                $locale
            )
            ->setHint(
                \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
                0
            )
            ->getResult()
        ;
    }
}
